<script setup lang="ts">
import NavBar from '../components/NavBar.vue';
</script>

<template>
  <div class="landing">
    <NavBar theme="light" />
    <div class="privacy-policy-container">
    <h1>Privacy Policy</h1>
    <p class="privacy-policy-updated">Last updated: 8 September 2026</p>
    <div class="privacy-policy-content">
        <div class="privacy-policy-content-item">
            <h3>1. Introduction</h3>
            <p>FlueHero operates the Fluemingo mobile application (hereinafter potentially referred to as "the App").<br/> 
                This Privacy Policy section is intended to inform you clearly and transparently about the personal data we collect, how we use it, and the rights you hold in relation to it.<br/>
                By using Fluemingo, you agree to the practices described in this policy.<br/>
                FlueHero is committed to protecting your privacy and ensuring the security of your personal data.
            </p>
        </div>
        <div class="privacy-policy-content-item">
            <h3>2. Data Controller</h3>
            <p>Fluemingo is operated by FlueHero, a trading name of Florent GALLOIS, registered as a sole trader (auto-entrepreneur) in France under SIRET n°82308601200023.<br/>
                Publisher: FlueHero<br>
                Application: Fluemingo<br>
                For any questions regarding this Privacy Policy, you may contact us at: contact@fluemingo-app.com
            </p>
        </div>
        <div class="privacy-policy-content-item">
            <h3>3. Data We Collect</h3>
            <div class="privacy-policy-content-item-subsection">
            <h4>3.1 Identification Data</h4>
            <p>When you create an account on Fluemingo, we collect the following categories of data:</p>
            <ul>
                <li>First name and last name</li>
                <li>Email address</li>
                <li>A user identifier generated by the App to link your account to your content</li>
            </ul>
        </div>
        <div class="privacy-policy-content-item-subsection">
            <h4>3.2 App Usage Data</h4>
            <p>When you use Fluemingo, we may collect the following categories of data:</p>
            <ul>
                <li>Articles listened to or currently in progress</li>
                <li>Audiobooks listened to or currently in progress</li>
                <li>Vocabulary saved and recorded by the user</li>
                <li>Product interaction data (screens viewed, features used, session frequency and duration)</li>
            </ul>
            </div>
        <div class="privacy-policy-content-item-subsection">
            <h4>3.3 Device and Technical Data</h4>
            <p>The App and the third-party services listed in section 7 collect the following technical data:</p>
            <ul>
                <li>Device identifiers (advertising identifier, vendor identifier, or an equivalent identifier generated by the SDKs we use)</li>
                <li>Device and operating system information (model, OS version, language, country)</li>
                <li>Installation, first-launch and app-opening events, and the marketing campaign or link that led to the installation</li>
                <li>Purchase and subscription data (subscription status, renewals, cancellations), excluding your payment card details, which are handled solely by Apple and Google</li>
                <li>Push notification token, if you have accepted notifications</li>
            </ul>
            <p>This technical data is used for analytics, marketing attribution, subscription management and notification delivery, as described in sections 4 and 7. It is not used for advertising targeting, and we do not sell it.</p>
            </div>
        </div>
            <div class="privacy-policy-content-item">
                <h3>4. Purposes of Processing</h3>
                <p>The data we collect is used for the following purposes:</p>
                <ul>
                    <li>Creating and managing your user account</li>
                    <li>Personalizing your learning experience (progress tracking, recommendations)</li>
                    <li>Synchronizing your vocabulary and audiobook library across your devices</li>
                    <li>Managing your subscription and access to paid features</li>
                    <li>Measuring the audience and performance of the App (analytics), and attributing installations to the marketing campaign they originate from</li>
                    <li>Improving our services and features</li>
                    <li>Sending account-related communications (updates, important notifications) and, if you have accepted them, push notifications</li>
                </ul>
            </div>
            <div class="privacy-policy-content-item">
                <h3>5. Legal Basis for Processing</h3>
                <p>The processing of your personal data is based on the following legal grounds:</p>
                <ul>
                    <li>Performance of a contract: processing is necessary to provide the Fluemingo service (account management, synchronization, content delivery, subscription management).</li>
                    <li>Legitimate interest: continuous improvement of our services based on usage data, measurement of the audience and of the effectiveness of our marketing campaigns.</li>
                    <li>Consent: for any optional processing (e.g. push and marketing notifications, and access to the advertising identifier where your device requires it), your explicit consent will be requested and may be withdrawn at any time in your device settings.</li>
                </ul>
            </div>
            <div class="privacy-policy-content-item">
                <h3>6. Data Retention</h3>
                <ul>
                    <li>Your data is retained for as long as your account remains active. Upon account deletion, your personal data will be erased within 30 days, unless otherwise required by law.</li>
                    <li>Technical and analytics data held by the providers listed in section 7 is retained according to their own retention periods, and in any case no longer than 24 months after your last activity.</li>
                </ul>
            </div>
            <div class="privacy-policy-content-item">
                <h3>7. Data Sharing and Third-Party Services</h3>
                <p>FlueHero does not sell or rent your personal data to third parties. Your data may be shared only in the following cases:</p>
                <ul>
                    <li>With technical service providers (hosting, cloud infrastructure) operating under our control and in strict compliance with this policy.</li>
                    <li>With the third-party providers listed below, which act as processors on our behalf and receive only the data required for their specific function.</li>
                    <li>When required by law or as part of legal proceedings.</li>
                    <li>In the event of a merger, acquisition, or asset transfer, with prior notice to users.</li>
                </ul>
                <p>The App integrates the following third-party services:</p>
                <ul>
                    <li><strong>AppsFlyer</strong> (marketing attribution and analytics) — receives device identifiers, installation and app-opening events, and technical device data, in order to attribute installations to the campaign they originate from and to measure the performance of the App. <a href="https://www.appsflyer.com/legal/services-privacy-policy/" target="_blank" rel="noopener">Privacy policy</a></li>
                    <li><strong>RevenueCat</strong> (subscription management) — receives your user identifier, a device identifier and your purchase and subscription data, in order to manage your access to paid features. <a href="https://www.revenuecat.com/privacy/" target="_blank" rel="noopener">Privacy policy</a></li>
                    <li><strong>OneSignal</strong> (push notifications) — receives your notification token, a device identifier and basic device data, in order to deliver the notifications you have accepted. <a href="https://onesignal.com/privacy_policy" target="_blank" rel="noopener">Privacy policy</a></li>
                </ul>
            </div>
            <div class="privacy-policy-content-item">
                <h3>8. International Data Transfers</h3>
                <p>Some of the providers listed in section 7 are established outside the European Union, in particular in the United States. Such transfers are governed by the European Commission's Standard Contractual Clauses or by an adequacy decision, in accordance with Chapter V of the GDPR.</p>
            </div>
            <div class="privacy-policy-content-item">
                <h3>9. Data Security</h3>
                <p>We implement appropriate technical and organizational measures to protect your data against unauthorized access, loss, destruction, or disclosure. These measures include encryption of data in transit (HTTPS/TLS) and at rest.</p>
            </div>
            <div class="privacy-policy-content-item">
                <h3>10. Your Rights</h3>
                In accordance with the General Data Protection Regulation (GDPR) and applicable laws, you have the following rights:
                <ul>
                    <li>Right of access: obtain a copy of the data we hold about you.</li>
                    <li>Right to rectification: correct inaccurate or incomplete data.</li>
                    <li>Right to erasure: request the deletion of your data, except when retention is required by law. You can also delete your account, and all data attached to it, directly from the App in the account settings.</li>
                    <li>Right to data portability: receive your data in a structured, machine-readable format.</li>
                    <li>Right to object: object to certain processing of your data, including analytics and marketing attribution.</li>
                    <li>Right to restriction: request the temporary suspension of processing.</li>
                </ul>
                <p>
                    To exercise these rights, contact us at: contact@fluemingo-app.com. We will respond within 30 days.
                </p>
                <p>
                    You may also limit the collection of technical data at any time from your device settings: on iOS, by refusing app tracking or by enabling "Limit Ad Tracking"; on Android, by deleting or opting out of the advertising identifier. Push notifications can be disabled in the same settings.
                </p>
            </div>
            <div class="privacy-policy-content-item">
                <h3>11. Cookies and Similar Technologies</h3>
                <p>
                    The Fluemingo marketing website may use cookies for analytics (audience measurement) and functional purposes. You can configure your browser to reject cookies.
                </p>
                <p>
                    The mobile App does not use cookies. It does, however, use software development kits (SDKs) that rely on device identifiers and local storage for the purposes described in sections 3.3 and 7.
                </p>
            </div>
            <div class="privacy-policy-content-item">
                <h3>12. Children's Data</h3>
                <p>
                    Fluemingo is not intended for children under the age of 13. We do not knowingly collect personal data from minors. If you believe a child has provided us with data without parental consent, please contact us so we can delete it.
                </p>
            </div>
            <div class="privacy-policy-content-item">
                <h3>13. Changes to This Policy</h3>
                <p>
                    FlueHero reserves the right to modify this Privacy Policy at any time. In the event of a material change, we will notify you via the App or by email at least 15 days before the changes take effect. The current version is always available on our website.
                </p>
            </div>
            <div class="privacy-policy-content-item">
                <h3>14. Contact &amp; Complaints</h3>
                For any questions or complaints regarding the handling of your personal data, you may contact us:
                <ul>
                    <li>By email: contact@fluemingo-app.com</li>
                </ul>
                You also have the right to lodge a complaint with the supervisory authority in your country (e.g., in France: CNIL – www.cnil.fr; in the UK: ICO – www.ico.org.uk).
            </div>
    </div>
    <Footer />
  </div>
</div>
</template>



<style scoped>
.landing {
  background-color: var(--color-background);
  min-height: 100vh;
}

.privacy-policy-container {
  width: min(100%, var(--page-max-width-narrow));
  margin: 0 auto;
  padding: clamp(2rem, 5vw, 3rem) var(--page-gutter);
}
.privacy-policy-updated {
  margin: 0.5rem 0 0;
  opacity: 0.7;
  font-size: 0.9rem;
}
.privacy-policy-content {
  padding: 1rem 0 0;
}
.privacy-policy-content-item {
  padding: 1rem 0;
  margin-bottom: 1rem;
}
.privacy-policy-content-item-subsection {
  padding: 1rem 0 0;
  margin-bottom: 1rem;
}

.privacy-policy-content-item ul,
.privacy-policy-content-item-subsection ul {
  padding-left: 1.25rem;
  list-style-type: disc;
}

@media (max-width: 640px) {
  .privacy-policy-container {
    padding-top: 1.5rem;
  }
}
</style>
